<template src="./AccountHub.html"></template>

<script setup>
import {
  authUser,
  canUseSocial,
  closeProfilePanel,
  fetchSocialOverview,
  friends,
  openConversation,
  openFriendProfile,
  openProfilePanel,
  pendingRequests,
  removeFriend,
  respondFriendRequest,
  respondRoomInvite,
  searchSocialUsers,
  sendFriendRequest,
  sendSocialMessage,
  socialActiveTab,
  socialChatDraft,
  socialChatFriendId,
  socialChatMessages,
  socialFriendNotificationCount,
  socialInvitePrompt,
  socialNotificationCount,
  socialProfileLoading,
  socialProfileVisible,
  socialSearchEmptyMessage,
  socialSearchKeyword,
  socialSearchResults,
  logout,
  profile,
  records,
  isViewingSelf,
  displayInitial,
  levelProgressWidth,
  activeChatFriend,
  mobileFriendView,
  handleAccountClick,
  openSelfProfile,
  confirmRemoveFriend,
  openFriendConversation,
  backToFriendList,
  formatTime,
} from "./AccountHub.js";

const _exposeToHtml = {
  authUser,
  canUseSocial,
  closeProfilePanel,
  fetchSocialOverview,
  friends,
  openConversation,
  openFriendProfile,
  openProfilePanel,
  pendingRequests,
  removeFriend,
  respondFriendRequest,
  respondRoomInvite,
  searchSocialUsers,
  sendFriendRequest,
  sendSocialMessage,
  socialActiveTab,
  socialChatDraft,
  socialChatFriendId,
  socialChatMessages,
  socialFriendNotificationCount,
  socialInvitePrompt,
  socialNotificationCount,
  socialProfileLoading,
  socialProfileVisible,
  socialSearchEmptyMessage,
  socialSearchKeyword,
  socialSearchResults,
  logout,
  profile,
  records,
  isViewingSelf,
  displayInitial,
  levelProgressWidth,
  activeChatFriend,
  mobileFriendView,
  handleAccountClick,
  openSelfProfile,
  confirmRemoveFriend,
  openFriendConversation,
  backToFriendList,
  formatTime,
};
</script>

<style scoped src="./AccountHub.css"></style>
