"""Generate 小桃's tutorial speech with the selected VoiceDesign style and per-line delivery settings.

Requires a CUDA-enabled PyTorch environment and requirements-xiaotao-tts.txt.
The original invitation recording is preserved. New lines use VoiceDesign directly.
Existing clips are reused only when their text, description and file hash match.
"""
import argparse
import hashlib
import importlib.metadata
import html
import json
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile
import time

ROOT = Path(__file__).resolve().parents[1]
MODEL_ID = "Qwen/Qwen3-TTS-12Hz-1.7B-VoiceDesign"
VOICE_DIR = ROOT / "poker-frontend/asset-sources/voices/xiaotao"
OUTPUT = ROOT / "poker-frontend/public/audios/xiaotao"
CATALOG = ROOT / "poker-frontend/src/tutorial/tutorialVoiceCatalog.js"
SEED = 42


def read_lines():
    script = "import { getTutorialVoiceLines } from './poker-frontend/src/tutorial/tutorialVoiceLines.js'; console.log(JSON.stringify(getTutorialVoiceLines()));"
    result = subprocess.run(["node", "--input-type=module", "-e", script], cwd=ROOT,
                            capture_output=True, text=True, encoding="utf-8", check=True)
    return json.loads(result.stdout)


def fingerprint(text, reference_hash, description, recipe=None):
    parameters = (json.dumps(recipe, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
                  if recipe else str(SEED) + description)
    return hashlib.sha256((MODEL_ID + reference_hash + parameters + text).encode("utf-8")).hexdigest()


def line_recipe(line, voice):
    profile_name = voice.get("line_profiles", {}).get(line["id"])
    if not profile_name:
        return None
    profile = voice["delivery_profiles"][profile_name]
    return {"profile": profile_name, "seed": profile.get("seed", voice.get("generation_seed", SEED)),
            "description": voice["design_description"] + profile["description_suffix"],
            "generation": {"language": "Chinese", "non_streaming_mode": True, "max_new_tokens": 2048,
                           **profile["generation"]}, "audio_processing": profile["audio_processing"]}


def encode_mp3(wave_path, target):
    import imageio_ffmpeg
    temporary = target.with_suffix(".part.mp3")
    subprocess.run([imageio_ffmpeg.get_ffmpeg_exe(), "-hide_banner", "-loglevel", "error", "-y",
                    "-i", str(wave_path), "-codec:a", "libmp3lame", "-b:a", "96k",
                    "-ar", "24000", "-ac", "1", str(temporary)], check=True)
    if temporary.stat().st_size < 5000:
        raise RuntimeError(f"Audio file is too small: {target.name}")
    temporary.replace(target)


def write_catalog(lines, clips):
    voices = {line["text"]: f"/audios/xiaotao/{clips[line['id']]['file']}" for line in lines
              if line["id"] in clips and clips[line["id"]].get("text") == line["text"]
              and (OUTPUT / clips[line["id"]]["file"]).is_file()}
    CATALOG.write_text("// Generated by scripts/generate_xiaotao_audios.py.\n"
                       'export const TUTORIAL_VOICE_NAME = "元气甜妹";\n'
                       "export const TUTORIAL_VOICES = " + json.dumps(voices, ensure_ascii=False, indent=2) + ";\n" +
                       "export const TUTORIAL_VOICE_TIMINGS = " + json.dumps({line["text"]: clips[line["id"]]["subtitle_cues"]
                           for line in lines if line["id"] in clips and clips[line["id"]].get("text") == line["text"]
                           and clips[line["id"]].get("subtitle_cues")}, ensure_ascii=False, separators=(",", ":")) + ";\n",
                       encoding="utf-8")


def write_listening_page(lines, clips):
    sections = {"invitation": ("开场邀请", []), "basic": ("基础教程", []),
                "advanced": ("锦囊教程", []), "other": ("退出与异常提示", [])}
    for line in lines:
        clip = clips.get(line["id"])
        if not clip or clip["text"] != line["text"]:
            continue
        identity = line["id"]
        group = identity.split("-")[0] if "-" in identity else identity
        if group not in sections:
            group = "other"
        label = {"invitation": "原始邀请试音" if clip["method"] == "original_selected_audition" else "开场邀请",
                 "exit": "退出教学", "error": "异常提示"}.get(identity)
        if label is None:
            parts = identity.split("-")
            label = "完成教程" if parts[1] == "complete" else f"第 {parts[1]} 节 · 第 {parts[2]} 句"
        url = "/audios/xiaotao/" + clip["file"]
        if clip.get("recipe"):
            label += " · 修正版"
        sections[group][1].append(
            f'<article><h3>{html.escape(label)} <small>{clip["duration_seconds"]:.1f} 秒</small></h3>'
            f'<p>{html.escape(line["text"])}</p>'
            f'<audio controls preload="none" data-source="{html.escape(url, quote=True)}" '
            f'aria-label="{html.escape(sections[group][0] + label, quote=True)}"></audio></article>')
    content = "\n".join(f'<section><h2>{html.escape(title)}</h2><div class="clips">' +
                        "\n".join(items) + '</div></section>' for title, items in sections.values())
    page = '''<!doctype html>
<html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>小桃教程配音试听</title><link rel="icon" href="data:,"><style>
*{box-sizing:border-box}body{margin:0;background:#160f0a;color:#f4e7d0;font:16px/1.7 "Microsoft YaHei",sans-serif}
main{max-width:1120px;margin:auto;padding:28px 20px 60px}h1{font-size:28px;margin:0 0 8px}header p{color:#ceb992;margin:0}
section{margin-top:32px}h2{font-size:21px;border-bottom:1px solid #c6a36b55;padding-bottom:8px}
.clips{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}article{padding:18px;background:#2a1714;border:1px solid #c6a36b55;border-radius:10px}
h3{font-size:17px;margin:0}small{float:right;font-size:13px;font-weight:normal;color:#ceb992}article p{font-size:15px;margin:12px 0;min-height:4em}audio{width:100%}
@media(max-width:680px){main{padding:20px 14px 40px}.clips{grid-template-columns:1fr}h1{font-size:24px}article p{min-height:0}}
</style></head><body><main><header><h1>小桃 · 元气甜妹</h1><p>小桃的新手教程配音，可逐句试听。</p></header>
''' + content + '''</main><script>
const prefix = location.protocol === "file:" ? "../../../public" : "";
const audios = [...document.querySelectorAll("audio")];
for (const audio of audios) {
  audio.src = prefix + audio.dataset.source;
  audio.addEventListener("play", () => audios.forEach(other => { if (other !== audio) other.pause(); }));
}
</script></body></html>\n'''
    (VOICE_DIR / "listen.html").write_text(page, encoding="utf-8")


def main():
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model", default=MODEL_ID, help="Hugging Face model id or a local model directory")
    parser.add_argument("--limit", type=int, help="Generate at most this many new clips")
    parser.add_argument("--prepare-only", action="store_true", help="Prepare the selected invitation and audio catalog")
    args = parser.parse_args()
    if args.limit is not None and args.limit < 1:
        parser.error("--limit must be a positive integer")
    voice = json.loads((VOICE_DIR / "voice.json").read_text(encoding="utf-8"))
    if voice["design_model"] != MODEL_ID or not voice["design_description"].strip():
        raise RuntimeError("The selected VoiceDesign model and description are required.")
    description = voice["design_description"]
    reference = VOICE_DIR / "reference.wav"
    if not reference.is_file():
        raise FileNotFoundError(f"The selected reference voice is missing: {reference}")
    lines = read_lines()
    reference_text = (VOICE_DIR / "reference.txt").read_text(encoding="utf-8").strip()
    reference_hash = hashlib.sha256(reference.read_bytes()).hexdigest()
    OUTPUT.mkdir(parents=True, exist_ok=True)
    manifest_path = VOICE_DIR / "generated-audios.json"
    manifest = json.loads(manifest_path.read_text(encoding="utf-8")) if manifest_path.exists() else {"clips": {}}
    manifest.update(voice="元气甜妹", model=MODEL_ID, reference_sha256=reference_hash, seed=SEED,
                    method="voice_design", design_description=description,
                    generation={"language": "Chinese", "non_streaming_mode": True, "max_new_tokens": 2048},
                    audio_conversion="gradio_peak_normalized_pcm16")
    manifest["status"] = "partial"

    def record(line, duration, filename=None, method="voice_design"):
        recipe = line_recipe(line, voice)
        filename = filename or line["id"] + ("." + recipe["profile"] if recipe else "") + ".mp3"
        previous = manifest["clips"].get(line["id"], {})
        manifest["clips"][line["id"]] = {"text": line["text"], "duration_seconds": round(duration, 2),
            "file": filename, "method": method,
            "fingerprint": fingerprint(line["text"], reference_hash, description, recipe),
            "sha256": hashlib.sha256((OUTPUT / filename).read_bytes()).hexdigest()}
        if recipe:
            manifest["clips"][line["id"]]["recipe"] = recipe
        clip = manifest["clips"][line["id"]]
        if all(previous.get(key) == clip[key] for key in ["text", "sha256", "fingerprint"]):
            for key in ["subtitle_cues", "subtitle_alignment"]:
                if key in previous:
                    clip[key] = previous[key]
        manifest_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    def current(line):
        clip = manifest["clips"].get(line["id"], {})
        path = OUTPUT / clip.get("file", line["id"] + ".mp3")
        return (path.is_file() and clip.get("fingerprint") == fingerprint(line["text"], reference_hash, description, line_recipe(line, voice))
                and clip.get("method") in {"voice_design", "original_selected_audition"}
                and hashlib.sha256(path.read_bytes()).hexdigest() == clip.get("sha256"))

    import soundfile as sf
    if reference_text == lines[0]["text"]:
        target = OUTPUT / "invitation.wav"
        if not target.exists() or hashlib.sha256(target.read_bytes()).hexdigest() != reference_hash:
            shutil.copy2(reference, target)
        record(lines[0], sf.info(str(reference)).duration, "invitation.wav", "original_selected_audition")
    write_catalog(lines, manifest["clips"])
    pending = [line for line in lines if not current(line)]
    manifest["status"] = "partial" if pending else "complete"
    manifest_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    if args.prepare_only:
        write_listening_page(lines, manifest["clips"])
        print(json.dumps({"state": "prepared", "published_clips": len(manifest["clips"]),
                          "planned_lines": len(lines)}, ensure_ascii=False), flush=True)
        return

    if args.limit is not None:
        pending = pending[:args.limit]
    if not pending:
        write_listening_page(lines, manifest["clips"])
        print("All requested clips are current.")
        return
    import numpy as np
    import torch
    from qwen_tts import Qwen3TTSModel
    if not torch.cuda.is_available():
        raise RuntimeError("CUDA-enabled PyTorch is required for local tutorial voice generation.")
    torch.set_num_threads(4)
    print(json.dumps({"state": "loading_model", "model": args.model, "pending": len(pending)}), flush=True)
    model = Qwen3TTSModel.from_pretrained(args.model, device_map="cuda:0", dtype=torch.bfloat16,
                                        attn_implementation="sdpa", low_cpu_mem_usage=True)
    provenance = Path(args.model) / "download-provenance.json"
    if provenance.is_file():
        manifest["model_revision"] = json.loads(provenance.read_text(encoding="utf-8"))["revision"]
    manifest["status"] = "generating"
    manifest["runtime"] = {name: importlib.metadata.version(name)
                           for name in ["qwen-tts", "transformers", "torch", "soundfile", "imageio-ffmpeg"]}
    for index, line in enumerate(pending, 1):
        started = time.monotonic()
        print(json.dumps({"state": "generating", "id": line["id"], "index": index, "total": len(pending), "text": line["text"]}, ensure_ascii=False), flush=True)
        recipe = line_recipe(line, voice)
        torch.manual_seed(recipe["seed"] if recipe else SEED)
        with torch.inference_mode():
            wavs, sample_rate = model.generate_voice_design(text=line["text"],
                instruct=recipe["description"] if recipe else description,
                **(recipe["generation"] if recipe else manifest["generation"]))
        audio = np.asarray(wavs[0], dtype=np.float32)
        duration = len(audio) / sample_rate
        if not np.isfinite(audio).all() or not 1 < duration < 60 or float(np.sqrt(np.mean(audio ** 2))) < 0.002:
            raise RuntimeError(f"Invalid generated audio: {line['id']}")
        with tempfile.TemporaryDirectory(prefix="xiaotao-") as temporary:
            wave_path = Path(temporary) / "audio.wav"
            if recipe:
                processing = recipe["audio_processing"]
                audio = audio / np.max(np.abs(audio)) * processing["peak"]
                ramp = min(int(sample_rate * processing["fade_ms"] / 1000), len(audio) // 2)
                if ramp:
                    audio[:ramp] *= np.linspace(0, 1, ramp, dtype=np.float32)
                    audio[-ramp:] *= np.linspace(1, 0, ramp, dtype=np.float32)
                sf.write(wave_path, audio, sample_rate, subtype="PCM_16")
            else:
                # Match the official audition's Gradio WAV conversion.
                pcm = (audio / np.max(np.abs(audio)) * 32767).astype(np.int16)
                sf.write(wave_path, pcm, sample_rate, subtype="PCM_16")
            filename = line["id"] + ("." + recipe["profile"] if recipe else "") + ".mp3"
            encode_mp3(wave_path, OUTPUT / filename)
        record(line, duration)
        write_catalog(lines, manifest["clips"])
        print(json.dumps({"state": "complete", "id": line["id"], "duration": round(duration, 2),
                          "elapsed_seconds": round(time.monotonic() - started, 1)}), flush=True)
    manifest["status"] = "complete" if all(current(line) for line in lines) else "partial"
    manifest_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    write_listening_page(lines, manifest["clips"])
    print(json.dumps({"state": "finished", "clips": len(manifest["clips"]), "status": manifest["status"]}), flush=True)


if __name__ == "__main__":
    main()
