<template src="./GameBoard.html"></template>

<script setup>
import BattleEffectsLayer from "./BattleEffectsLayer.vue";
import BattlePhaseNotice from "./BattlePhaseNotice.vue";
// 【核心修复 1】：移除了 onMounted 中的 playBGM("Normal")。
import { computed } from "vue";
import * as liveBindings from "./GameBoard.js";
const props = defineProps({ session: { type: Object, default: null } });
const tutorialMode = !!props.session;
const battleSession = props.session?.battleSession || null;
const tutorialPhase = computed(() => props.session?.phase.value || "");
const canBoardAction = (action) => props.session?.policy.canAction(action) ?? true;
const cardIsSelectable = (card) => props.session?.policy.canSelect(card) ?? true;
const cardIsTarget = (card) => props.session?.policy.isTarget(card) ?? false;
const actionIsTarget = (action) => props.session?.policy.isActionTarget(action) ?? false;
const boardCardId = (card) => card.suit === "JOKER" ? card.rank : card.suit + card.rank;
const {
  phaseNotice,
  effectsSettingsOpen,
  effectsQuality,
  audioLevels,
  userId,
  otherPlayers,
  currentTurn,
  countdown,
  activeActionTexts,
  activeEmojis,
  currentAoeType,
  pendingAoePlayers,
  aoeInitiator,
  tableCards,
  lastPlayPlayer,
  sortedTableCards,
  isSpectator,
  myStatus,
  handCards,
  amIPendingAoe,
  selectedCards,
  aoeAnimCards,
  sortedHandCards,
  showEmojiPanel,
  emojiList,
  winner,
  winningCards,
  killText,
  sortedWinningCards,
  getCardImageUrl,
  handleImageError,
  toggleSelect,
  respondAoe,
  discardAoe,
  playCards,
  replaceCard,
  passTurn,
  toggleEmojiPanel,
  sendEmoji,
  exitGame,
  returnToRoom,
  onlyHasScrolls,
  soundStatus,
  toggleSound,
  isShuffling,
  warningUserId,
  mySkill,
  showSkillSelection,
  showGuanxingModal,
  guanxingCards,
  selectedGuanxingCards,
  selectSkill,
  toggleGuanxingSelect,
  confirmGuanxing,
  playBGM,
  skillCountdown,
  showWgfdModal,
  wgfdCards,
  selectedWgfdCard,
  toggleWgfdSelect,
  confirmWgfd,
  confirmGushouDiscard,
  jdsrTarget,
  jdsrInitiator,
  luanjianInitiator, // <--- 干净的唯一引入
  kurouUseCount,
  kurouUsesThisTurn,
  kurouAwakened,
  guixinDisabled,
  guixinPendingPasser,
  showGuixinModal,
  confirmGuixinDecision,
  confirmKurouAwakenDiscard,
  skipKurouAwakenDiscard,
  tieqiJudgeCards,
} = props.session?.bindings || liveBindings;

// ====== 【核心修复 2：防脱发防白屏机制】 ======
const _exposeToHtml = {
  tutorialMode, tutorialPhase, battleSession, canBoardAction, cardIsSelectable, cardIsTarget, actionIsTarget, boardCardId,
  phaseNotice,
  effectsSettingsOpen,
  effectsQuality,
  audioLevels,
  userId,
  otherPlayers,
  currentTurn,
  countdown,
  activeActionTexts,
  activeEmojis,
  currentAoeType,
  pendingAoePlayers,
  aoeInitiator,
  tableCards,
  lastPlayPlayer,
  sortedTableCards,
  isSpectator,
  myStatus,
  handCards,
  amIPendingAoe,
  selectedCards,
  aoeAnimCards,
  sortedHandCards,
  showEmojiPanel,
  emojiList,
  winner,
  winningCards,
  killText,
  sortedWinningCards,
  getCardImageUrl,
  handleImageError,
  toggleSelect,
  respondAoe,
  discardAoe,
  playCards,
  replaceCard,
  passTurn,
  toggleEmojiPanel,
  sendEmoji,
  exitGame,
  returnToRoom,
  onlyHasScrolls,
  soundStatus,
  toggleSound,
  isShuffling,
  warningUserId,
  mySkill,
  showSkillSelection,
  showGuanxingModal,
  guanxingCards,
  selectedGuanxingCards,
  selectSkill,
  toggleGuanxingSelect,
  confirmGuanxing,
  playBGM,
  skillCountdown,
  showWgfdModal,
  wgfdCards,
  selectedWgfdCard,
  toggleWgfdSelect,
  confirmWgfd,
  confirmGushouDiscard,
  jdsrTarget,
  jdsrInitiator,
  luanjianInitiator, // <--- 干净的唯一暴露
  kurouUseCount,
  kurouUsesThisTurn,
  kurouAwakened,
  guixinDisabled,
  guixinPendingPasser,
  showGuixinModal,
  confirmGuixinDecision,
  confirmKurouAwakenDiscard,
  skipKurouAwakenDiscard,
  tieqiJudgeCards,
};
</script>

<style scoped src="./GameBoard.css"></style>
